### ISSUE TITLE
Where to find the datasets?

### ISSUE THREAD

**Issue by guillemram97** [naver-ai/hypermix#1]
I can't find the datasets at https://github.com/huggingface/datasets/tree/master/datasets, and I suspect they may have changed their names/structure (as in subj-> subjqa). Where can I find the version of datasets that you used?

**Comment by kaniblu** [comment]
Hi guillemram97, the dataset can be found at https://huggingface.co/gpt3mix. We have made our new movie review dataset public (`rt20`) as well.

**Comment by guillemram97** [comment]
There are sst2 and rt20 in that repository. Where can I find the other datasets?

**Comment by kaniblu** [comment]
We have plans to update more datasets in the future but we don't have a specific timeline. Meanwhile, you could prepare custom datasets referencing the data format.
